# Generated by Django 5.2.7 on 2025-12-16 17:23

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KVKK', 'KVKK / DSGVO'), ('PRIVACY', 'Gizlilik Politikası'), ('TERMS', 'Kullanıcı Sözleşmesi'), ('COOKIE', 'Çerez Politikası')], max_length=10, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('require_consent', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adresi')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Müşteri Rolü')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Çalışan Rolü')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Yönetici Rolü')),
                ('role', models.CharField(default='customer', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama (Türkçe)')),
                ('description_de', models.TextField(blank=True, verbose_name='Açıklama (Almanca)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Kategori Görseli')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Hizmet Kategorisi',
                'verbose_name_plural': 'Hizmet Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('description', models.TextField(verbose_name='Hizmet Detayları')),
                ('price_info', models.CharField(blank=True, max_length=255, verbose_name='Fiyat Bilgisi/Aralığı')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Ortalama Süre (dk)')),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='account.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Hizmet Detayı',
                'verbose_name_plural': 'Hizmet Detayları',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('approved_appointments', models.IntegerField(default=0)),
                ('rejected_appointments', models.IntegerField(default=0)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='account.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Tarih/Saat')),
                ('end_time', models.DateTimeField(verbose_name='Bitiş Tarih/Saat')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('COMPLETED', 'Tamamlandı'), ('CANCELED', 'İptal Edildi')], default='PENDING', max_length=10, verbose_name='Randevu Durumu')),
                ('request_details', models.TextField(blank=True, verbose_name='Müşteri Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_appointments', to='account.customer', verbose_name='Müşteri')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='account.service', verbose_name='Hizmet')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_appointments', to='account.worker', verbose_name='Çalışan')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='work_samples/')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_samples', to='account.service', verbose_name='İlgili Hizmet')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='account.worker', verbose_name='Çalışan Profili')),
            ],
            options={
                'verbose_name': 'Yapılan İş Örneği',
                'verbose_name_plural': 'Yapılan İş Örnekleri',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Haftanın Günü')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('is_active', models.BooleanField(default=True)),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='account.worker', verbose_name='Çalışan')),
            ],
            options={
                'verbose_name': 'Çalışan Müsaitliği',
                'verbose_name_plural': 'Çalışan Müsaitlikleri',
                'unique_together': {('worker_profile', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
