# Generated by Django 5.2.7 on 2025-12-23 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category_price_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='accept_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
