# Generated by Django 5.2.8 on 2025-12-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_musteri_user_operator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetsuper',
            name='operatorler',
            field=models.ManyToManyField(blank=True, to='account.operator'),
        ),
    ]
